# Generated by Django 4.2.11 on 2025-07-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='consumer_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='consumer',
            name='ssn',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='status',
            field=models.CharField(choices=[('INACTIVE', 'Inactive'), ('PAID_IN_FULL', 'Paid In Full'), ('IN_COLLECTION', 'In Collection')], default='IN_COLLECTION', max_length=20),
        ),
    ]
